import crypto from "node:crypto";
import { compareCursorPaths } from "./compare.ts";

const INVENTORY_PATH = "reports/inventory-sha256.json";

interface GeneratedFileBytes {
  content: Buffer;
}

interface InventoryEntry {
  path: string;
  sha256: string;
  bytes: number;
}

function record(value: unknown, label: string): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`Cursor inventory ${label} must be an object`);
  }
  return value as Record<string, unknown>;
}

/** Validate that the inventory is an exact, non-self-referential description of generated bytes. */
export function validateCursorInventory(
  document: unknown,
  actual: ReadonlyMap<string, GeneratedFileBytes>,
): void {
  const inventory = record(document, "document");
  if (inventory.profile !== "full") throw new Error("Cursor inventory profile must be full");
  if (!Array.isArray(inventory.files)) throw new Error("Cursor inventory files must be an array");

  const entries: InventoryEntry[] = inventory.files.map((value, index) => {
    const entry = record(value, `entry ${index}`);
    if (typeof entry.path !== "string") throw new Error(`Cursor inventory entry ${index} path must be a string`);
    if (typeof entry.sha256 !== "string" || !/^[a-f0-9]{64}$/.test(entry.sha256)) {
      throw new Error(`Cursor inventory entry ${entry.path} has an invalid SHA-256`);
    }
    if (!Number.isSafeInteger(entry.bytes) || (entry.bytes as number) < 0) {
      throw new Error(`Cursor inventory entry ${entry.path} has an invalid byte count`);
    }
    return { path: entry.path, sha256: entry.sha256, bytes: entry.bytes as number };
  });

  const paths = entries.map((entry) => entry.path);
  if (paths.includes(INVENTORY_PATH)) throw new Error("Cursor inventory must not include itself");
  if (new Set(paths).size !== paths.length) throw new Error("Cursor inventory contains a duplicate path");
  if (paths.join("\0") !== [...paths].sort(compareCursorPaths).join("\0")) {
    throw new Error("Cursor inventory paths are not code-point sorted");
  }

  const expectedPaths = [...actual.keys()]
    .filter((filePath) => filePath !== INVENTORY_PATH)
    .sort(compareCursorPaths);
  if (paths.join("\0") !== expectedPaths.join("\0")) {
    throw new Error("Cursor inventory path set differs from generated output");
  }

  for (const entry of entries) {
    const bytes = actual.get(entry.path)!.content;
    const sha256 = crypto.createHash("sha256").update(bytes).digest("hex");
    if (entry.sha256 !== sha256) throw new Error(`Cursor inventory hash differs for ${entry.path}`);
    if (entry.bytes !== bytes.length) throw new Error(`Cursor inventory byte count differs for ${entry.path}`);
  }

  const totals = record(inventory.totals, "totals");
  if (totals.files !== entries.length) throw new Error("Cursor inventory file total differs from entries");
  const bytes = entries.reduce((total, entry) => total + entry.bytes, 0);
  if (totals.bytes !== bytes) throw new Error("Cursor inventory byte total differs from entries");
}
