// Which repository paths the Codex build owns.
//
// `build-codex.ts` writes exactly one root: the `axiom-codex/` plugin tree. It
// does NOT touch `.agents/plugins/marketplace.json` (the Codex marketplace
// manifest is version-free and hand-maintained). Kept in one place so the two
// sites that must agree cannot drift:
//   - set-version.js — the --tag preflight, which since 2026-09-05 runs
//     build-codex and must not treat the output it just wrote as an unrelated
//     dirty-tree change
//   - this module's test, which pins the boundary
//
// Deliberately narrow. The preflight's job is refusing to tag a dirty tree, so
// this absolves only paths the script itself regenerates — never a stray sibling
// like `axiom-codex-notes.md`.

const CODEX_PLUGIN_ROOT = 'axiom-codex/';

/**
 * True when `relativePath` is regenerated by `npm run build:codex`.
 *
 * @param {string} relativePath repository-relative path, either separator style
 * @returns {boolean}
 */
export function isCodexGeneratedPath(relativePath) {
  if (typeof relativePath !== 'string' || relativePath === '') return false;
  return relativePath.replaceAll('\\', '/').startsWith(CODEX_PLUGIN_ROOT);
}

export { CODEX_PLUGIN_ROOT };
