// Which repository paths the Cursor build owns.
//
// `writeCursorDistribution` (scripts/cursor/render.ts) writes exactly two roots:
// the `axiom-cursor/` plugin tree and `.cursor-plugin/marketplace.json`. Kept in
// one place so the two sites that must agree cannot drift:
//   - set-version.js — the --tag preflight, which now runs build-cursor and must
//     not treat the output it just wrote as an unrelated dirty-tree change
//   - this module's test, which pins the boundary
//
// Deliberately narrow. The preflight's job is refusing to tag a dirty tree, so
// this absolves only paths the script itself regenerates — never a stray sibling
// like `axiom-cursor-notes.md`.
//
// `axiom-codex/` is NOT this module's business, but it is no longer "unrelated"
// either: since 2026-09-05 set-version also runs build-codex, so the preflight
// composes this predicate with `isCodexGeneratedPath` from `codex-output.js`.

const CURSOR_MARKETPLACE_PATH = '.cursor-plugin/marketplace.json';
const CURSOR_PLUGIN_ROOT = 'axiom-cursor/';

/**
 * True when `relativePath` is regenerated by `npm run build:cursor`.
 *
 * @param {string} relativePath repository-relative path, either separator style
 * @returns {boolean}
 */
export function isCursorGeneratedPath(relativePath) {
  if (typeof relativePath !== 'string' || relativePath === '') return false;
  const normalized = relativePath.replaceAll('\\', '/');
  return normalized === CURSOR_MARKETPLACE_PATH || normalized.startsWith(CURSOR_PLUGIN_ROOT);
}

export { CURSOR_MARKETPLACE_PATH, CURSOR_PLUGIN_ROOT };
