/**
 * Keep sections that several plugin files must carry word-for-word in sync.
 *
 *   npm run build:shared              # copy each source section into its targets
 *   npm run build:shared -- --check   # verify only, non-zero on drift
 *
 * A shared section runs from its `## <heading>` line through an end-marker line,
 * `<!-- end of shared section; source: <source>, copies regenerated by npm run build:shared -->`,
 * written identically in the source and every copy. The end is explicit, not inferred from the next
 * heading: inferring it let a demoted heading or a stray fence in the source carry
 * the rest of the source into every copy, with every gate green.
 *
 * The source file owns the text and every target carries a generated copy. Edit the
 * source, then run the build: it overwrites each copy, including anything added to
 * a copy by hand. A drifted or malformed copy, an unregistered file carrying the
 * heading or the section's text, or a copy that would become a child skill's MCP
 * description fails `pre-deploy.ts` and `npm run test:unit`.
 *
 * Copies exist because not every harness reaches the source on the same path: an
 * MCP client can read a child skill without its router, and agents outside Claude
 * Code do not preload a router. Before adding a target, confirm that some harness
 * reads it without the source; otherwise point to the source.
 *
 * Writing is fail-closed: the build writes nothing while any check fails.
 */

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { parseReferenceFile } from "../axiom-mcp/src/loader/parser.ts";
import { isGeneratedSubSkill } from "./inline-auditors.ts";

export type SharedSection = { heading: string; source: string; targets: string[] };

export type SectionLookup =
  | { kind: "found"; start: number; end: number; fenceProblem?: string }
  | { kind: "missing" }
  | { kind: "ambiguous"; count: number }
  | { kind: "unterminated" };

/** Paths are relative to the plugin root, `.claude-plugin/plugins/axiom/`. */
export const SHARED_SECTIONS: SharedSection[] = [
  {
    heading: "Capture Build and Test Diagnostics",
    source: "skills/axiom-build/SKILL.md",
    targets: [
      "skills/axiom-build/skills/build-debugging.md",
      "agents/build-fixer.md",
      "agents/test-runner.md",
    ],
  },
];

/** Paragraphs at least this long are distinctive enough to identify a pasted copy. */
export const MIN_SHARED_PARAGRAPH = 200;

export function endMarkerFor(spec: SharedSection): string {
  return `<!-- end of shared section; source: ${spec.source}, copies regenerated by npm run build:shared -->`;
}

// CommonMark: up to three spaces of indentation. Four or more is an indented code
// line, and treating it as a fence misreads real plugin files (storage-diag.md).
const FENCE_OPEN = /^ {0,3}(`{3,}|~{3,})(.*)$/;
const CHILD_SKILL = /^skills\/[^/]+\/skills\/[^/]+\.md$/;

type Fence = { char: string; length: number; line: number };

/**
 * CommonMark fence tracking: a fence closes only on a line of the same character,
 * at least as long, with nothing after it, and a backtick line whose info string
 * holds a backtick is not a fence line at all. Returns the fence still open after
 * `line`, and records a likely-missing closer: an opening line with an info
 * string inside an open fence of the same kind.
 */
function stepFence(open: Fence | undefined, line: string, index: number) {
  const match = FENCE_OPEN.exec(line);
  if (!match) return { open };
  const [, run, info] = match;
  if (run[0] === "`" && info.includes("`")) return { open };
  if (!open) return { open: { char: run[0], length: run.length, line: index } };
  if (run[0] !== open.char || run.length < open.length) return { open };
  if (info.trim() === "") return { open: undefined };
  return {
    open,
    problem: `opens a code fence at line ${index + 1} inside the fence opened at line ${
      open.line + 1
    } (missing closing fence?)`,
  };
}

/** Line range [start, end) of the section, end marker included. */
export function findSection(markdown: string, heading: string, endMarker: string): SectionLookup {
  const lines = markdown.split("\n");
  const title = `## ${heading}`;
  const starts: number[] = [];
  let open: Fence | undefined;
  for (const [i, line] of lines.entries()) {
    const wasOpen = open;
    ({ open } = stepFence(open, line, i));
    if (!wasOpen && !open && line.trimEnd() === title) starts.push(i);
  }
  if (starts.length === 0) return { kind: "missing" };
  if (starts.length > 1) return { kind: "ambiguous", count: starts.length };

  const start = starts[0];
  const marker = lines.findIndex((line, i) => i > start && line.trimEnd() === endMarker);
  if (marker < 0) return { kind: "unterminated" };

  let fenceProblem: string | undefined;
  open = undefined;
  for (let i = start + 1; i < marker; i++) {
    const step = stepFence(open, lines[i], i);
    open = step.open;
    fenceProblem ??= step.problem;
  }
  if (open && !fenceProblem) {
    fenceProblem = `has a code fence opened at line ${
      open.line + 1
    } that is still open at the end marker`;
  }
  const end = marker + 1;
  return fenceProblem ? { kind: "found", start, end, fenceProblem } : { kind: "found", start, end };
}

/** `undefined` unless the section is found. */
export function replaceSection(
  markdown: string,
  heading: string,
  endMarker: string,
  section: string,
): string | undefined {
  const found = findSection(markdown, heading, endMarker);
  if (found.kind !== "found") return undefined;
  const lines = markdown.split("\n");
  return [...lines.slice(0, found.start), section, ...lines.slice(found.end)].join("\n");
}

type Located =
  | { kind: "located"; text: string; start: number; end: number }
  | { kind: "unusable"; error: string };

/** The section in one registered file, or why it cannot be compared or written. */
function locate(file: string, content: string | undefined, spec: SharedSection): Located {
  const title = `"## ${spec.heading}"`;
  const end = endMarkerFor(spec);
  const isSource = file === spec.source;
  if (content === undefined) {
    return {
      kind: "unusable",
      error: isSource
        ? `${file}: file not found (source of ${title})`
        : `${file}: file not found (registered in SHARED_SECTIONS)`,
    };
  }
  if (content.includes("\r")) {
    return { kind: "unusable", error: `${file}: CRLF line endings; shared sections need LF` };
  }
  const found = findSection(content, spec.heading, end);
  switch (found.kind) {
    case "missing":
      return {
        kind: "unusable",
        error: isSource
          ? `${file}: source section ${title} not found`
          : `${file}: ${title} not found — add the heading and \`${end}\` where the copy belongs, then run \`npm run build:shared\`, or unregister the file`,
      };
    case "ambiguous":
      return { kind: "unusable", error: `${file}: ${title} appears ${found.count} times` };
    case "unterminated":
      return {
        kind: "unusable",
        error: `${file}: ${title} has no end marker; add \`${end}\` on its own line after the copy`,
      };
  }
  if (found.fenceProblem) {
    return { kind: "unusable", error: `${file}: ${title} ${found.fenceProblem}` };
  }
  return {
    kind: "located",
    text: content.split("\n").slice(found.start, found.end).join("\n"),
    start: found.start,
    end: found.end,
  };
}

/**
 * True when the MCP server would describe this child skill with a line from the
 * section. Uses MCP's own parser, so the rule cannot drift from the one it guards.
 */
function sectionBecomesDescription(file: string, content: string, copy: Located): boolean {
  if (copy.kind !== "located") return false;
  const [, suite, , name] = file.split("/");
  const description = parseReferenceFile(content, name, suite).description;
  if (!description) return false;
  const lines = content.split("\n");
  const title = lines.findIndex((line) => /^#\s+/.test(line));
  const line = lines.findIndex((text, i) => i > title && text.trim() === description);
  return line >= copy.start && line < copy.end;
}

/** Mistakes in SHARED_SECTIONS itself. Each would otherwise do nothing, silently. */
function registryErrors(specs: SharedSection[]): string[] {
  const errors: string[] = [];
  const count = (items: string[], item: string) => items.filter((i) => i === item).length;
  const headings = specs.map((spec) => spec.heading);
  for (const heading of new Set(headings)) {
    const n = count(headings, heading);
    if (n > 1) errors.push(`SHARED_SECTIONS: "## ${heading}" is registered ${n} times`);
  }
  for (const spec of specs) {
    const title = `"## ${spec.heading}"`;
    if (spec.targets.length === 0) errors.push(`SHARED_SECTIONS: ${title} has no targets`);
    if (spec.targets.includes(spec.source)) {
      errors.push(`SHARED_SECTIONS: ${spec.source} is a target of its own ${title}`);
    }
    for (const target of new Set(spec.targets)) {
      const n = count(spec.targets, target);
      if (n > 1) errors.push(`SHARED_SECTIONS: ${target} is listed ${n} times for ${title}`);
    }
  }
  return errors;
}

/**
 * Each file's content with every registered section it carries removed, or
 * `undefined` for a registered file whose section cannot be located: its own error
 * already blocks, and matching its text would report the same problem twice.
 */
function outsideRegisteredSections(
  specs: SharedSection[],
  files: Record<string, string>,
): Record<string, string | undefined> {
  const masked: Record<string, string | undefined> = {};
  for (const [file, content] of Object.entries(files)) {
    const lines = content.split("\n");
    let unlocatable = false;
    for (const spec of specs) {
      if (file !== spec.source && !spec.targets.includes(file)) continue;
      const found = findSection(content, spec.heading, endMarkerFor(spec));
      if (found.kind === "found" && !found.fenceProblem) lines.fill("", found.start, found.end);
      else unlocatable = true;
    }
    masked[file] = unlocatable ? undefined : lines.join("\n");
  }
  return masked;
}

/** The section's paragraphs long enough to identify a copy, end marker removed. */
function distinctiveParagraphs(spec: SharedSection, text: string): string[] {
  const end = endMarkerFor(spec);
  return text
    .split(/\n\s*\n/)
    .map((p) => p.split("\n").filter((line) => line !== end).join("\n"))
    .filter((p) => p.length >= MIN_SHARED_PARAGRAPH);
}

/**
 * `files` maps plugin-relative paths to content and must include every plugin
 * markdown file, so a copy pasted into an unregistered file is caught too.
 * `previous` holds earlier versions of the registered files (HEAD, or the tree
 * before a sync): their section text is also searched for, so a stray copy of
 * text the source has since changed is still caught.
 */
export function sharedSectionErrors(
  specs: SharedSection[],
  files: Record<string, string>,
  previous: Record<string, string>[] = [],
): string[] {
  const registry = registryErrors(specs);
  if (registry.length > 0) return registry;
  const masked = outsideRegisteredSections(specs, files);
  const everyRegistered = new Set(specs.flatMap((spec) => [spec.source, ...spec.targets]));
  return [
    ...specs.flatMap((spec) => specErrors(spec, files, masked, previous, everyRegistered)),
    ...sharedOwnershipErrors(specs, files),
  ];
}

/** A paragraph in two specs' sections has two sources, and the copies drift apart. */
function sharedOwnershipErrors(specs: SharedSection[], files: Record<string, string>): string[] {
  const sections = specs.map((spec) => locate(spec.source, files[spec.source], spec));
  const errors: string[] = [];
  for (const [i, a] of specs.entries()) {
    const sectionA = sections[i];
    if (sectionA.kind !== "located") continue;
    for (const [j, b] of specs.entries()) {
      const sectionB = sections[j];
      if (j <= i || sectionB.kind !== "located") continue;
      if (distinctiveParagraphs(a, sectionA.text).some((p) => sectionB.text.includes(p))) {
        errors.push(
          `${b.source}: "## ${b.heading}" repeats text from "## ${a.heading}" (${a.source}); give each paragraph one owning section`,
        );
      }
    }
  }
  return errors;
}

function specErrors(
  spec: SharedSection,
  files: Record<string, string>,
  masked: Record<string, string | undefined>,
  previous: Record<string, string>[],
  everyRegistered: Set<string>,
): string[] {
  const title = `"## ${spec.heading}"`;
  const end = endMarkerFor(spec);
  const source = locate(spec.source, files[spec.source], spec);
  if (source.kind !== "located") return [source.error];

  const errors: string[] = [];
  for (const file of [spec.source, ...spec.targets]) {
    const copy = file === spec.source ? source : locate(file, files[file], spec);
    if (copy.kind !== "located") {
      errors.push(copy.error);
    } else if (copy.text !== source.text) {
      errors.push(
        `${file}: ${title} differs from ${spec.source} — edit ${spec.source}, not this copy, then run \`npm run build:shared\` (it overwrites the copy)`,
      );
    } else if (CHILD_SKILL.test(file) && sectionBecomesDescription(file, files[file], copy)) {
      errors.push(
        `${file}: ${title} comes before the skill's first paragraph, which MCP uses as the skill's description — move the section below that paragraph`,
      );
    }
  }

  // Text matching runs on content outside every registered section; a paragraph in
  // two specs' sections is sharedOwnershipErrors' business. Text from an earlier
  // version counts only in unregistered files: in a registered file it is usually a
  // paragraph just moved out of the section, which is a legitimate edit.
  const own = new Set([spec.source, ...spec.targets]);
  const current = distinctiveParagraphs(spec, source.text);
  const earlier = new Set<string>();
  for (const version of previous) {
    for (const file of own) {
      const before = locate(file, version[file], spec);
      if (before.kind !== "located") continue;
      for (const p of distinctiveParagraphs(spec, before.text)) {
        if (!current.includes(p)) earlier.add(p);
      }
    }
  }
  for (const file of Object.keys(files).sort()) {
    // Generated auditor sub-skills mirror agents/ and have their own gate (12d-bis).
    if (CHILD_SKILL.test(file) && isGeneratedSubSkill(files[file])) continue;
    const outside = masked[file];
    const carries = (paragraphs: Iterable<string>) =>
      outside !== undefined && [...paragraphs].some((p) => outside.includes(p));
    const carriesHeading = !own.has(file) &&
      findSection(files[file], spec.heading, end).kind !== "missing";
    if (own.has(file) && carries(current)) {
      errors.push(
        `${file}: repeats text from ${title} outside its section; keep the text in one place`,
      );
    } else if (
      carriesHeading || carries(current) || (!everyRegistered.has(file) && carries(earlier))
    ) {
      errors.push(
        `${file}: carries ${title} or its text but is not registered in SHARED_SECTIONS — register it as a target (it needs the heading and end marker), or replace the copied text with a pointer to ${spec.source}`,
      );
    }
  }
  return errors;
}

/**
 * Copy every source section into its targets, applying specs in order to one
 * working set so specs that share a target do not overwrite each other. A spec
 * whose source cannot be read changes nothing; a target that cannot be located
 * safely is skipped. Callers must not write anything when `errors` is non-empty.
 */
export function syncSharedSections(
  specs: SharedSection[],
  files: Record<string, string>,
): { files: Record<string, string>; changed: string[]; errors: string[] } {
  const registry = registryErrors(specs);
  if (registry.length > 0) return { files: { ...files }, changed: [], errors: registry };
  const working = { ...files };
  const changed = new Set<string>();
  const errors: string[] = [];
  for (const spec of specs) {
    const source = locate(spec.source, working[spec.source], spec);
    if (source.kind !== "located") {
      errors.push(source.error);
      continue;
    }
    for (const target of spec.targets) {
      const copy = locate(target, working[target], spec);
      if (copy.kind !== "located") {
        errors.push(copy.error);
        continue;
      }
      const next = replaceSection(working[target], spec.heading, endMarkerFor(spec), source.text);
      if (next !== undefined && next !== working[target]) {
        working[target] = next;
        changed.add(target);
      }
    }
  }
  return { files: working, changed: [...changed], errors };
}

function readPluginMarkdown(pluginDir: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const entry of fs.readdirSync(pluginDir, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) continue;
    const full = path.join(entry.parentPath, entry.name);
    files[path.relative(pluginDir, full).split(path.sep).join("/")] = fs.readFileSync(full, "utf8");
  }
  return files;
}

/**
 * The HEAD version of each of `files` (paths relative to `dir`). A file new since
 * HEAD has no committed version, which is expected and skipped. No HEAD at all, or
 * a file git cannot read, is reported as a warning, since the stale-text check is
 * then weaker than it looks.
 */
export function readCommittedVersions(
  dir: string,
  files: string[],
): { versions: Record<string, string>; warnings: string[] } {
  const git = (args: string[]) => spawnSync("git", args, { cwd: dir, encoding: "utf8" });
  if (git(["rev-parse", "--verify", "-q", "HEAD"]).status !== 0) {
    return {
      versions: {},
      warnings: [
        "no committed version to compare with (not a git work tree, or no HEAD); stale copies of earlier section text are not checked",
      ],
    };
  }
  const versions: Record<string, string> = {};
  const warnings: string[] = [];
  for (const file of files) {
    if (git(["cat-file", "-e", `HEAD:./${file}`]).status !== 0) continue;
    const shown = git(["show", `HEAD:./${file}`]);
    if (shown.status === 0) versions[file] = shown.stdout;
    else warnings.push(`could not read ${file} at HEAD: ${shown.stderr.trim()}`);
  }
  return { versions, warnings };
}

const registeredFiles =
  () => [...new Set(SHARED_SECTIONS.flatMap((s) => [s.source, ...s.targets]))];

export function checkSharedSections(pluginDir: string): { errors: string[]; warnings: string[] } {
  const committed = readCommittedVersions(pluginDir, registeredFiles());
  return {
    errors: sharedSectionErrors(SHARED_SECTIONS, readPluginMarkdown(pluginDir), [
      committed.versions,
    ]),
    warnings: committed.warnings,
  };
}

if (process.argv[1] && fs.realpathSync(process.argv[1]) === import.meta.filename) {
  const pluginDir = path.join(import.meta.dirname, "../.claude-plugin/plugins/axiom");
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error(
      `unknown arguments: ${args.join(" ")}\nUsage: node scripts/shared-sections.ts [--check]`,
    );
    process.exit(2);
  }
  const fail = (errors: string[], note: string) => {
    for (const message of errors) console.error(`  ✗ ${message}`);
    console.error(`✗ ${note}`);
    process.exit(1);
  };
  const committed = readCommittedVersions(pluginDir, registeredFiles());
  for (const warning of committed.warnings) console.error(`  ! ${warning}`);
  if (args[0] === "--check") {
    const { errors } = checkSharedSections(pluginDir);
    if (errors.length > 0) fail(errors, "shared sections out of sync");
  } else {
    // Check the result before writing any of it, so a stray copy or a misplaced
    // section stops the build with the tree untouched.
    const before = readPluginMarkdown(pluginDir);
    const sync = syncSharedSections(SHARED_SECTIONS, before);
    if (sync.errors.length > 0) fail(sync.errors, "nothing written");
    const after = sharedSectionErrors(SHARED_SECTIONS, sync.files, [before, committed.versions]);
    if (after.length > 0) fail(after, "nothing written");
    for (const target of sync.changed) {
      fs.writeFileSync(path.join(pluginDir, target), sync.files[target]);
      console.log(`updated ${target}`);
    }
  }
  console.log(`✓ ${SHARED_SECTIONS.length} shared section(s) in sync`);
}
